version: '3.0'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - 9200:9200
    networks:
      - db_network
    environment:
      - discovery.type=single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - db_network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
